/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PatientDetails } from "./PatientDetails";
import { PatientDetailsCountArgs } from "./PatientDetailsCountArgs";
import { PatientDetailsFindManyArgs } from "./PatientDetailsFindManyArgs";
import { PatientDetailsFindUniqueArgs } from "./PatientDetailsFindUniqueArgs";
import { CreatePatientDetailsArgs } from "./CreatePatientDetailsArgs";
import { UpdatePatientDetailsArgs } from "./UpdatePatientDetailsArgs";
import { DeletePatientDetailsArgs } from "./DeletePatientDetailsArgs";
import { PatientDetailsService } from "../patientDetails.service";
@graphql.Resolver(() => PatientDetails)
export class PatientDetailsResolverBase {
  constructor(protected readonly service: PatientDetailsService) {}

  async _patientDetailsItemsMeta(
    @graphql.Args() args: PatientDetailsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PatientDetails])
  async patientDetailsItems(
    @graphql.Args() args: PatientDetailsFindManyArgs
  ): Promise<PatientDetails[]> {
    return this.service.patientDetailsItems(args);
  }

  @graphql.Query(() => PatientDetails, { nullable: true })
  async patientDetails(
    @graphql.Args() args: PatientDetailsFindUniqueArgs
  ): Promise<PatientDetails | null> {
    const result = await this.service.patientDetails(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PatientDetails)
  async createPatientDetails(
    @graphql.Args() args: CreatePatientDetailsArgs
  ): Promise<PatientDetails> {
    return await this.service.createPatientDetails({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => PatientDetails)
  async updatePatientDetails(
    @graphql.Args() args: UpdatePatientDetailsArgs
  ): Promise<PatientDetails | null> {
    try {
      return await this.service.updatePatientDetails({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PatientDetails)
  async deletePatientDetails(
    @graphql.Args() args: DeletePatientDetailsArgs
  ): Promise<PatientDetails | null> {
    try {
      return await this.service.deletePatientDetails(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
